title: tech-fundamentals
description: >-
  Learn the core concepts you need to understand technology and how to use it to
  your advantage
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
